((docker nil)
 (magit-branch nil)
 (magit-branch-configure nil)
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-merge nil)
 (magit-push nil)
 (magit-remote
  ("-f"))
 (magit-remote\.<remote>\.*url "https://gitlab.com/nicktee/emacs-reveal-howto.git" ""))
